name: PR Quality
on: [pull_request]
jobs:
  none:
    name: No build tags
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        go: ['1.13', '1.14', '1.15']
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: go mod download
      - name: Format Test # ty Ikkerens
        run: diff <(gofmt -d ./...) <(echo -n)
      - name: test
        run: go test -v -race ./...
  buildtags:
    name: Build tags
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildtag: [disgord_diagnosews, disgordperf]
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Get dependencies
        run: go mod download
      - name: test
        run: go test -tags=${{ matrix.buildtag }} -v -race ./...
